AWSTemplateFormatVersion: '2010-09-09'
Description: A template to deploy an EC2 instance with an Elastic IP, NGINX, Let's Encrypt SSL, and a MySQL RDS instance.

Parameters:
  DomainName:
    Type: String
    Description: Fully-qualified domain name to link to the SSL certificate, e.g., 6529prenode.yercooldomain.wtf
  HostedZoneId:
    Type: String
    Description: The ID of the existing Route 53 hosted zone.
  AdminEmail:
    Type: String
    Description: Email address for SSL certificate registration and alerts.
  AMIId:
    Type: AWS::EC2::Image::Id
    Description: AMI ID for the Ubuntu server.
  MasterUserPassword:
    Type: String
    NoEcho: true
    Description: Master password for the RDS instance - should be very long and random.
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instance.
  AlchemyAPIKey:
    Type: String
    Description: API key for accessing the Alchemy service.
  RepoBranch:
    Type: String
    Description: Use the default, unless you are testing a different branch.
    Default: main
  OwnerAddress:
    Type: String
    Description: Ethereum address of the prenode owner.
  OwnerSignatureHash:
    Type: String
    Description: Hash of the owner's address signing a message containing only the prenode domain name.
  

Resources:
  PrenodeDNSRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Ref DomainName
      Type: A
      TTL: '300'
      ResourceRecords:
        - !GetAtt PrenodeEIP.PublicIp

  PrenodeVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16

  PrenodeInternetGateway:
    Type: AWS::EC2::InternetGateway
    DependsOn: PrenodeVPC

  PrenodeGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref PrenodeVPC
      InternetGatewayId: !Ref PrenodeInternetGateway

  PrenodeRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref PrenodeVPC

  PrenodeRoute:
    Type: AWS::EC2::Route
    DependsOn: PrenodeGateway
    Properties:
      RouteTableId: !Ref PrenodeRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref PrenodeInternetGateway

  PrenodeSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref PrenodeVPC
      CidrBlock: 10.0.1.0/24
      AvailabilityZone: 
        Fn::Select:
          - 0
          - Fn::GetAZs: !Ref 'AWS::Region'

  PrenodeSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref PrenodeVPC
      CidrBlock: 10.0.2.0/24
      AvailabilityZone: 
        Fn::Select:
          - 1
          - Fn::GetAZs: !Ref 'AWS::Region'

  PrenodeSubnetRouteTableAssociation1:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PrenodeSubnet1
      RouteTableId: !Ref PrenodeRouteTable

  PrenodeSubnetRouteTableAssociation2:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PrenodeSubnet2
      RouteTableId: !Ref PrenodeRouteTable

  PrenodeServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow access to ports 80, 443, and 22 for SSH.
      VpcId: !Ref PrenodeVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0

  PrenodeRDSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: RDS security group allowing access from EC2
      VpcId: !Ref PrenodeVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          SourceSecurityGroupId: !Ref PrenodeServerSecurityGroup

  PrenodeDatabase:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceClass: db.t4g.micro
      AllocatedStorage: 100
      Engine: mysql
      MasterUsername: admin
      MasterUserPassword: !Ref MasterUserPassword
      DBName: tdhprenode
      VPCSecurityGroups: [!Ref PrenodeRDSSecurityGroup]
      DBSubnetGroupName: !Ref PrenodeDBSubnetGroup

  PrenodeDBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Subnet group for RDS instance
      SubnetIds: 
        - !Ref PrenodeSubnet1
        - !Ref PrenodeSubnet2

  PrenodeEIP:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc
      InstanceId: !Ref PrenodeEC2Instance
      
  PrenodeEC2Instance:
    Type: AWS::EC2::Instance
    DependsOn: PrenodeDatabase
    Properties:
      InstanceType: t3.small
      KeyName: !Ref KeyName
      ImageId: !Ref AMIId
      SubnetId: !Ref PrenodeSubnet1
      SecurityGroupIds: [!Ref PrenodeServerSecurityGroup]
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          apt-get update
          apt-get install -y mysql-client

          # Wait for the RDS instance to be available
          RDS_ENDPOINT=${PrenodeDatabase.Endpoint.Address}
          MASTER_PASSWORD="${MasterUserPassword}"
          USER_PASSWORD=$(python3 -c "import sys; print(sys.argv[1][:len(sys.argv[1])//2])" "${MasterUserPassword}")

          # Create the database, write-enabled user, and read-only user
          mysql -h $RDS_ENDPOINT -u admin -p${MasterUserPassword} -e "
          CREATE DATABASE IF NOT EXISTS tdhprenode;
          CREATE USER IF NOT EXISTS 'prenodeuser'@'%' IDENTIFIED WITH 'mysql_native_password' BY '$USER_PASSWORD';
          GRANT ALL PRIVILEGES ON tdhprenode.* TO 'prenodeuser'@'%';
          CREATE USER IF NOT EXISTS 'prenodeuser-read'@'%' IDENTIFIED WITH 'mysql_native_password' BY '$USER_PASSWORD-read';
          GRANT SELECT ON tdhprenode.* TO 'prenodeuser-read'@'%';"
      
          apt-get install -y nginx python3-pip certbot python3-certbot-nginx
          systemctl start nginx
          certbot --non-interactive --nginx --redirect -d ${DomainName} --agree-tos -m ${AdminEmail}
          echo '
          server {
              root /var/www/html;
              index index.html;
              server_name ${DomainName}; # managed by Certbot
              listen [::]:443 ssl ipv6only=on; # managed by Certbot
              listen 443 ssl; # managed by Certbot
              ssl_certificate /etc/letsencrypt/live/${DomainName}/fullchain.pem; # managed by Certbot
              ssl_certificate_key /etc/letsencrypt/live/${DomainName}/privkey.pem; # managed by Certbot
              include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
              ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
              location / {
                proxy_pass http://localhost:3000;
              }
          }
          server {
              if ($host = ${DomainName}) {
                  return 301 https://$host$request_uri;
              } # managed by Certbot
              listen 80 ;
              listen [::]:80 ;
              server_name ${DomainName};
              return 404; # managed by Certbot
          }' | sudo tee /etc/nginx/sites-enabled/default > /dev/null
          certbot install --cert-name ${DomainName}
          systemctl reload nginx
          su -l ubuntu -c "
            cd ~
            git clone --branch ${RepoBranch} https://github.com/6529-Collections/6529-Prenode.git 
            cd 6529-Prenode
            echo '
            DB_HOST=${PrenodeDatabase.Endpoint.Address}
            DB_PORT=3306
            DB_NAME=tdhprenode
            DB_USER=prenodeuser
            DB_PASS=$USER_PASSWORD
            DB_HOST_READ=${PrenodeDatabase.Endpoint.Address}
            DB_USER_READ=prenodeuser-read
            DB_PASS_READ=$USER_PASSWORD-read
            ALCHEMY_API_KEY=${AlchemyAPIKey}
            OWNER_ADDRESS=${OwnerAddress}
            OWNER_SIGNATURE_HASH=${OwnerSignatureHash}
            ' > .env.prenode
            bash scripts/setup.sh
            sudo env PATH=$PATH:/usr/local/bin /usr/local/lib/node_modules/pm2/bin/pm2 startup systemd -u ubuntu --hp /home/ubuntu
            npm run restore # Restore database from the latest snapshot
            bash scripts/start.sh # Start the server with pm2
          "
      BlockDeviceMappings:
        - DeviceName: "/dev/sda1"
          Ebs:
            VolumeSize: 30
      Tags:
      - Key: Name
        Value: PrenodeEC2Instance

Outputs:
  WebsiteURL:
    Description: URL of the website
    Value: !Sub "https://${DomainName}/"
  DBEndpoint:
    Description: Endpoint for RDS database instance
    Value: !GetAtt PrenodeDatabase.Endpoint.Address
  ElasticIPAddress:
    Description: "The Elastic IP address associated with the instance"
    Value: !GetAtt PrenodeEIP.PublicIp
    Export:
      Name: !Sub "${AWS::StackName}-EIP"
